[package]
name = "simpleRedditApp-rust"
version = "0.1.0"
authors = ["zeke <eer2138@columbia.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
